### PR TITLE
enchancements redisson-quarkus-20 native mode and config

### PR DESCRIPTION
**Pull request by ineednousername**
created enhancements for running the redisson extension in quarkus and especially native mode.
- got rid of --allow-incomplete-classpath
- made bean runtime configureable
- removed some of offending spring dependencies from compilation tree (moved to spring specific impl of TaskInjector)
- added testcontainers to easily start up a redis instance (if a docker environment is available)
- upgraded to quarkus 2.0.3.Final
- use already existing netty extension
- changed only redisson-quarkus-20

### CODE REVIEW

**Comment by mrniko** [comment]
Thank you for proposed changes.

According to your descriptions, it covers 7 tasks. Please split it into PR per task.

**Comment by ineednousername** [comment]
> Thank you for proposed changes.
> 
> According to your descriptions, it covers 7 tasks. Please split it into PR per task.

Hi,

whats the point in doing that? Anyways those changes are dependent for example if I just create a PR to remove `--allow-incomplete-classpath` it would be meaningless since the native image would not work anymore.

The only things which could make sense but I don't see why it would make a practical difference would be splitting.
* upgraded to quarkus 2.0.3.Final
* made bean runtime configureable
* make native image build possible without --allow-incomplete-classpath

**Comment by mrniko** [comment]
> whats the point in doing that?

To understand which changes to related to task.

**Comment by mrniko** [comment]
any update?

**Review by Hot-Jazz-Holla — APPROVED** [review]

**Comment by mrniko** [comment]
@ineednousername 

Three tasks are enough.

**Comment by ineednousername** [comment]
@mrniko 
sorry for not reacting here. 
I will get back to this as soon as I have some time to work on my proposed changes.

**Comment by mrniko** [comment]
That's correct. Also please include only changed lines.

**Comment by ineednousername** [comment]
native image without --allow-incomplete-classpath --> most likely also relates to solve https://github.com/redisson/redisson/issues/3774

**Comment by mrniko** [comment]
Exactly 😊

**Comment by ineednousername** [comment]
>     * native image without --allow-incomplete-classpath

https://github.com/redisson/redisson/pull/3782

**Pull request closed without merging**
