### PR TITLE
Fixed - 100% usage by CommandsQueue in rare cases. #6153

### PR DESCRIPTION
**Pull request by Kicey**
There is also some problem after the original fix of issue #6153.

I think the actual reason of the deadlock is that the `CommandsQueue#write` are invoked twice in one stack. Obviously, it cannot obtain the lock at the second time.

I'm not sure what exactly causes the second time invocation of the `CommandsQueue#write`. But if there is no other problem, just turn the lock to a `ReentrantLock` to solve it.

### CODE REVIEW

**Comment by Kicey** [comment]
[deadklock.html.pdf](https://github.com/user-attachments/files/17168543/deadklock.html.pdf)
Here is the flame graph that the deadlock triggered again. `Thread#yeild` doesn't work.

**Comment by mrniko** [comment]
Can you reproduce it?

**Comment by mrniko** [comment]
Thanks for comment. Fixed in https://github.com/redisson/redisson/commit/01e1259eb9a6ed974c3393acdc7004767d588ffc

**Comment by Kicey** [comment]
> Can you reproduce it?

It's not easy to re produce normally. And I'm afraid that I can't provide productive environment stack or heap info.

But you can reproduce it by debug (change some variable to mock the slow or block I/O).

Configure redisson to use just one netty thread, and one connection.

Execute a command with redisson normally. As screenshot below, you will be at `flush0` of netty `AbstractChannel`. 

Make `doWrite` at line 931 error (the easiest way I think is to create a NullPointerException), and enter the 933 line `handleWriteError` (it's better to change the t variable to be a IoException).

image

Then you should at `RedisExecuter#checkWriteFuture` as picture below shows, remember to change the attempt equals to attempts, to mock all the attempts failed.

image

Then you should at `RedisExecuter#releaseConnection`, remember to change it from 1 to 10, and restore it after the check of 606 line.

image

Then, you should at `AsyncSemaphore#tryRun` as below.

image

Here, try to invoke redisson to send a command to add a future into the `listeners`, then run into line 79 in the above picture. (Which cause the second time trying to obtain of the lock). 

Continue, you'll get a deadlock.

**Comment by Kicey** [comment]
> Thanks for comment. Fixed in [01e1259](https://github.com/redisson/redisson/commit/01e1259eb9a6ed974c3393acdc7004767d588ffc)

It works, but I think yield is not necessary. Feel free to close the pr.

**Pull request closed without merging**
