### PR TITLE
Feature - Netty native transport for `io_uring`

### LINKED ISSUE #5169: Support for `io_uring` via `TransportMode`
**Is your feature request related to a problem? Please describe.**

We are using `io_uring` with Micronaut now and we would like to use it with Redisson too.

**Describe the solution you'd like**

It would be cool if Redisson would add bindings for IOUring types and a `TransportMode.IO_URING` entry.

**Describe alternatives you've considered**

I don't think it is possible to use `io_uring` with Redisson unless these changes are made.

### PR DESCRIPTION
**Pull request by sgammon**
- add `TransportMode.IO_URING`
- add incubator uring dependency

Fixes and closes #5169

### CODE REVIEW

**Comment by sgammon** [comment]
@mrniko would you be willing to merge ?

**Comment by mrniko** [comment]
@sgammon yes

**Comment by mrniko** [comment]
Please complete all checks

**Comment by sgammon** [comment]
@mrniko fixed

**Comment by mrniko** [comment]
Thanks for contribution!

**Pull request merged**
