### PR TITLE
Avoid redisson fair lock blocking if there are lots of registered thr…

### PR DESCRIPTION
**Pull request by wuqian0808hundsun**
Signed-off-by:  wuqian30624@hundsun.com

If lots of thread registered in redission fair lock queue and timeout map, and all these threads got shutdown accidently. The another app which trys to reuse this fair lock will get blocked for a long time.
Add logic to clear those not used queue info.

### CODE REVIEW

**Comment by wuqian0808hundsun** [comment]
Is there anything else I should do or provide?

**Comment by wuqian0808hundsun** [comment]
@mrniko Kindly help to advise

**Comment by mrniko** [comment]
Please cover it by test.

**Comment by wuqian0808hundsun** [comment]
Test case added

**Comment by mrniko** [comment]
DCO check isn't passed

**Comment by wuqian0808hundsun** [comment]
DCO aaded

**Comment by mrniko** [comment]
Thanks for contribution!

**Comment by mrniko** [comment]
reverted https://github.com/redisson/redisson/pull/3186#issue-515204182

**Pull request merged**
