### PR TITLE
Add lua script loader

### PR DESCRIPTION
**Pull request by TDtianzhenjiu**
add a script loader, load Lua script from classloader resource

### CODE REVIEW

**Comment by mrniko** [comment]
You need to set `useScriptCache = true` setting instead

**Comment by TDtianzhenjiu** [comment]
> You need to set `useScriptCache = true` setting instead

@mrniko hello 
I provide a way to separate LUA script and java code, not only for caching scripts
lots of  LUA  script in java code not good for reading and understanding  script logic

**Comment by mrniko** [comment]
I'm sorry, but I would like to see a script with used parameters in the code.

**Comment by TDtianzhenjiu** [comment]
@mrniko  Well,  LuaScriptsLoader can be another choice at least.
1. you can use it when you won't see a script in the code
2. on the user level, can be a convenient tool to load scripts🙏

**Comment by mrniko** [comment]
I agree it might be useful to users. Can you add this feature to RScript object instead?

**Comment by TDtianzhenjiu** [comment]
> I agree it might be useful to users. Can you add this feature to RScript object instead?

@mrniko sure, already updated to RScript

**Comment by TDtianzhenjiu** [comment]
@mrniko HI
Could you approve this Or give some feedback?

**Comment by mrniko** [comment]
@TDtianzhenjiu Hi,

I expected to see more methods like scriptLoad(InputStream). Resources caching should be on application side, not Redisson

**Pull request closed without merging**
