### PR TITLE
Cluster runner extras

### PR DESCRIPTION
**Pull request by jackygurui**

### CODE REVIEW

**Comment by jackygurui** [comment]
Forgot to mention the commit #aaf3166 also fixed a bug where slots were incorrectly allocated to slave nodes instead of only for masters.

**Comment by mrniko** [comment]
Sorry, I forgot to push my fix for ClusterRunner. Could you rebase your changes?

**Comment by jackygurui** [comment]
Done :)

**Comment by mrniko** [comment]
Thanks!

**Pull request merged**
