### PR TITLE
Fix leaking Redisson/Executor/Threads during test execution

### LINKED ISSUE #693: Redisson JUnit tests due leaks connections/clients/threads
If you run the JUnit tests for Redisson a lot of client and their associated connections/threads are leaking because they are not properly shutdown. This will prevent the build to be successful on system with limited number of user-processes/open-files (i.e. MacOS El Capitain).

To verify this, build the project with an attached debugger and watch the constantly growing amount of threads.

### PR DESCRIPTION
**Pull request by smigfu**
CLOSES #693

### CODE REVIEW

**Comment by smigfu** [comment]
Please don't merge yet. The first upload is just a preview for now and I would like to add some annotations first since this is a lot of changed files =)

**Comment by smigfu** [comment]
1. Make it possible to identify threads started by redisson/netty. Added a configuration for the Thread prefixes of the EventLoops and Executors as well as set a identifiable thread name to the HashWheelTimer (https://github.com/redisson/redisson/pull/694/commits/aaf98b708d6ab16393b64bb4d84c1c5272a5bc4b, https://github.com/redisson/redisson/pull/694/commits/c334aebb45658ec8399aaa055506c15a579fa98a).

2. Instead of using a test hierarchy (BaseConcurrentTest, BaseTest, BaseReactiveTest) I outsourced the setup/after code into two TestRules (RedissonRule, RedisServerRule). By this the code doesn't need to be duplicated in the various BaseXXX classes) and proper shutdown of the instances obtained by these rules will be guaranteed (https://github.com/redisson/redisson/pull/694/commits/55b9344a37c8cce51d91e3ad2df5ade88054c623).

3. All redisson instances (RedissinClient/RedissonReactiveClient) will  be obtained through the RedissonRule and by that making sure that this instance is registered for shutdown after the test has finished. Both of them are conveniently defined as @ClassRule in the _only_ base class for tests allowing the server and clients to be created on a per TestSuite level (they don't get created for each single test but only once for all tests within one file, this is similar to what has happened before). The alternative would have been to find all instances in the test code where a client is initiated and making sure it will be closed properly (finally or a distinct register method in the base class).

3.  The biggest part of the review is the refactoring of the tests to use the TestRules. I hoped I have translated all of these properly into the new system. The neat thing is that if you watch the created/running threads with a debugger during the test execution you will see all threads are properly closed at the end of a test (https://github.com/redisson/redisson/pull/694/commits/1fa3ba73e6f4fdb43a87bfb887fc1340bfcede5d).

4. Last but not least I searched the code for all instances of Executors being created but never closed. In a second step these executors could be outsourced into a TestRule as well, but since this PR already contains a lot of files, I didn't do this here but just made sure that all are being shutDown (not always in a finally block) (https://github.com/redisson/redisson/pull/694/commits/a5158b34a7dfa072cfb51d6fafdeedf149419e67).

**Comment by smigfu** [comment]
Another advantage of the approach with TestRules later on is that you can create a (dynamic) TestSuite where you defined the rules as TestSuite level class rules. By that the Server has only to be started once for all tests (within the suite).

**Comment by smigfu** [comment]
I still have some failing tests though, which I need to investigate.

```
Failed tests: 
  RedissonLockTest.testAutoExpire:102 Transient lock has not expired automatically
  RedissonScoredSortedSetReactiveTest.testAddAndGet:325 expected:<12.0> but was:<11.0>
  RedissonSetCacheReactiveTest.testExpireOverwrite:84 expected:<[fals]e> but was:<[tru]e>
Tests in error: 
  RedissonBlockingQueueTest.testPollReattach:101 » ConditionTimeout Condition de...
  RedissonTest.testManyConnections » RedisConnection Can't init enough connectio...
  JCacheTest.test » RedisConnection Can't init enough connections amount! Only 0...
  RedissonSpringCacheTest.after:131->lambda$after$0:131 ClassCast java.lang.Stri...
```

**Comment by smigfu** [comment]
```RedissonLockTest.testAutoExpire:102 Transient lock has not expired automatically```

What I can see here is that the TTL of the lock is continuously prolonged by the RedissonLock#scheduleExpirationRenewal. Does this test work for you?. I.e. the following commands are executed on the redis server:

```

MONITOR
+OK
+1478691413.433073 [0 127.0.0.1:51659] "EVAL" "if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);" "1" "lock" "30000" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691413.433489 [0 lua] "exists" "lock"
+1478691413.433511 [0 lua] "hset" "lock" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34" "1"
+1478691413.433543 [0 lua] "pexpire" "lock" "30000"
+1478691423.520637 [0 127.0.0.1:51663] "EVAL" "if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); return 1; end; return 0;" "1" "lock" "30000" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691423.520776 [0 lua] "hexists" "lock" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691423.520798 [0 lua] "pexpire" "lock" "30000"
+1478691433.619792 [0 127.0.0.1:51662] "EVAL" "if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); return 1; end; return 0;" "1" "lock" "30000" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691433.619843 [0 lua] "hexists" "lock" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691433.619857 [0 lua] "pexpire" "lock" "30000"
+1478691443.719476 [0 127.0.0.1:51660] "EVAL" "if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); return 1; end; return 0;" "1" "lock" "30000" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691443.719559 [0 lua] "hexists" "lock" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691443.719584 [0 lua] "pexpire" "lock" "30000"
+1478691453.818683 [0 127.0.0.1:51664] "EVAL" "if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('pexpire', KEYS[1], ARGV[1]); return 1; end; return 0;" "1" "lock" "30000" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691453.818736 [0 lua] "hexists" "lock" "2294777a-352e-4f7d-ace3-0ffc99ac779e:34"
+1478691453.818751 [0 lua] "pexpire" "lock" "30000"
+1478691458.452905 [0 127.0.0.1:51665] "EXISTS" "lock"
+1478691458.468136 [0 127.0.0.1:51666] "FLUSHDB"
Connection closed by foreign host.
```

**Comment by smigfu** [comment]
The ```JCacheTest```which is failing expects a running server on port 6139 (as configured in ```redisson-jcache.json```). I guess this in only working in the Travis environment?

**Comment by mrniko** [comment]
@smigfu please extract commit aaf98b708d6ab16393b64bb4d84c1c5272a5bc4b to separate PR

**Comment by mrniko** [comment]
@smigfu `RedissonLockTest.testAutoExpire` test stop to work

**Comment by mrniko** [comment]
@jackygurui what do you think about changes?

**Comment by smigfu** [comment]
I have created https://github.com/redisson/redisson/pull/696 and will rebase this PR if it is merged.

regarding the failing test, do you have an idea what could be causing this (see my comment above about the prolongation of the lock)?

**Pull request closed without merging**
