### PR TITLE
Improvement - add other type in RType which Redisson used.

### PR DESCRIPTION
**Pull request by seakider**
I am not so sure : 
1. Whether these changes are necessary ? 
2. If necessary, ('none' type use "NONE" instand of 'null') is it the right change ?

### CODE REVIEW

**Comment by mrniko** [comment]
String parsing is made here org.redisson.client.protocol.convertor.TypeConvertor. I don't mind to move it to RType. `NONE` type should be avoided and `null` used instead. Like in current implementation.

**Comment by zyh-stu** [comment]
Is there a follow up to this question, the org.redisson.RedissonKeys#getType method doesn't work properly if no other types are added to the RType

**Comment by mrniko** [comment]
@zyh-stu 

Can you create an issue regarding this task?

**Comment by zyh-stu** [comment]
> @zyh-stu
> 
> Can you create an issue regarding this task?

Created #6102

**Pull request closed without merging**
