### PR TITLE
Add support for TOML configs (#4161)

### PR DESCRIPTION
**Pull request by ElizabethCody**
This PR is intended to add TOML configs support per issue #4161.

TOML configs can now be loaded via the `Config` API in addition to being automatically discovered by other middleware like Spring and Hibernate.

This PR includes changes to the tests for JCache and RedissonSessionManager. This was done to ensure coverage parity with the YAML code. If this isn't desirable, please let me know.

Please share your thoughts and feedback!

### CODE REVIEW

**Review by mrniko — CHANGES_REQUESTED** [review]
Thanks much for proposed changes! Currently I don't plan to remove JSON support in 3.x version. Can you suggest changes without removing JSON?

**Comment by MaxwellCody** [comment]
> Currently I don't plan to remove JSON support in 3.x version. Can you suggest changes without removing JSON?

Maybe I forgot to add it back somewhere, but as far as I can tell my changes leave the existing JSON code in tact. Several of the diffs may seem like the code is being removed, but I'm just moving it so the code attempts to parse as TOML before trying JSON.

There were a few instances I found where the code only handled YAML so I only updated with TOML support.

**Comment by mrniko** [comment]
Please correct all failed checks.

**Comment by mrniko** [comment]
Any update?

**Comment by mrniko** [comment]
Closed due to absence of any update

**Pull request closed without merging**
