### PR TITLE
fix the #827

### LINKED ISSUE #827: putIfAbsent followed by addAndGet causes bad argument #2 to 'unpack' (data string too short)
Hello , have peculiar situation where below works only first time around (reason for first API call is to establish "expire" on key as addAndGet does not allow one to specify expire)

so below works fine during first run, subsequent runs Redisson throws an exception (below at the end of this post)

thanks for any input on this

RMapCache<String, Object> mapCache = redisClient.getMapCache("test_put_if_absent");
Object  currValue = mapCache.putIfAbsent("4", 0L, 10000L, TimeUnit.SECONDS);
Object updatedValue = mapCache.addAndGet("4", 1L);
System.out.println("updatedValue: " + updatedValue);

------------

org.redisson.client.RedisException: ERR Error running script (call to f_04ca52da6f32fea58a7378efe5e857fbdc376470): @user_script:1: user_script:1: bad argument #2 to 'unpack' (data string too short) . channel: [id: 0xfe4a958b, /127.0.0.1:45434 => /127.0.0.1:6379] command: CommandData [promise=org.redisson.misc.RedissonPromise@34c88748[Not completed], command=(EVAL), params=[if redis.call('hexists', KEYS[1], ARGV[4]) == 0 then if tonumber(ARGV[1]) > 0 then redis.call('zadd'..., 3, test_put_if_absent, redisson__timeout__set:{test_put_if_absent}, redisson__idle__set:{test_put_if_absent}, 1490911908793, 0, 0, 4, 0], codec=org.redisson.codec.JsonJacksonCodec@7bb8b36e]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:267)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:127)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:831)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:346)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:254)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by jackygurui**
fixed #827 by extending addAndGet method and made it packed content aware

### CODE REVIEW

**Comment by andrewmilkowski** [comment]
this still fails for

RMapCache<String, Object> mapCache = redisClient.getMapCache("test_put_if_absent", StringCodec.INSTANCE);
Object currValue = mapCache.putIfAbsent("4", 0L, 10000L, TimeUnit.SECONDS);
Object updatedValue = mapCache.addAndGet("4", 1L);
System.out.println("updatedValue: " + updatedValue);

**Comment by jackygurui** [comment]
@andrewmilkowski can you try it again? Thanks!

**Comment by andrewmilkowski** [comment]
same issue... test run and failed on

RMapCache<String, Object> mapCache = redisClient.getMapCache("test_put_if_absent");
 Object  currValue = mapCache.putIfAbsent("4", 1.23, 10000L, TimeUnit.SECONDS);
 Object updatedValue = mapCache.addAndGet("4", 1L);
 System.out.println("updatedValue: " + updatedValue);

did git pull in the repo branch (below) then assembled using mvn clean install

git branch -a
* add-and-get-for-mapcache

git pull

giit log
commit 38c8ae6a78822f87c102f6566f39692a869748ab
Author: Rui Gu <jackygurui@gmail.com>
Date:   Tue Apr 4 16:53:47 2017 +0100

    checks and fixed a few more different usage

**Comment by jackygurui** [comment]
@andrewmilkowski The same test has been added and now passes. The only thing I need to point out is 
```java
RMapCache<String, Object> mapCache = redisClient.getMapCache("test_put_if_absent");
Object currValue = mapCache.putIfAbsent("4", 1.23, 10000L, TimeUnit.SECONDS);
Object updatedValue = mapCache.addAndGet("4", 1L);
// Value type actually determines the return type,   ^^^ it needs to be changed to 1D to work because 
// the existing value is not a long.
System.out.println("updatedValue: " + updatedValue);
```

**Comment by andrewmilkowski** [comment]
hi @jackygurui above with correct param (double) worked fine (thought it would cast somehow internally

so now this fails (we use BigDecimals) in our computations due to high precision

 RMapCache<String, Object> mapCache = redisClient.getMapCache("test_put_if_absent_3");
        Object  currValue = mapCache.putIfAbsent("4", new BigDecimal(0, MathContext.DECIMAL64), 10000L, TimeUnit.SECONDS);
        Object updatedValue = mapCache.addAndGet("4", new BigDecimal(1.24, MathContext.DECIMAL64));
        System.out.println("updatedValue: " + currValue);

**Comment by andrewmilkowski** [comment]
also @jackygurui  longs are now casting exceptions, if longs can be fixed (in priority) before decimals would be awesome for us for now


        RMapCache<String, Object> mapCache = redisClient.getMapCache("test_put_if_absent_L");
        Object currValue = mapCache.putIfAbsent("4", 1L, 10000L, TimeUnit.SECONDS);
        Object updatedValue = mapCache.addAndGet("4", 1L);
        System.out.println("updatedValue: " + updatedValue);

**Comment by andrewmilkowski** [comment]
looks like I need StringCodec.INSTANCE) ... as well thanks @jackygurui

**Comment by andrewmilkowski** [comment]
looks like I need StringCodec.INSTANCE) as well... trying with longs first then above with BigDecimal

**Comment by jackygurui** [comment]
@andrewmilkowski You are right, a "raw" codec is required to work, since the addAndGet internally needs to see the value as redis string in order to perform the calculation. It doesn't have the capability to decode and encode the value. 

Depends on what type of object the `map.get()` you want to return, you can choose to use StringCodec if you want it to return string, you can use DoubleCodec if you want it to return a double or LongCodec for long value or implement your own codec if you want anything different.

**Comment by andrewmilkowski** [comment]
unfortunately map contains String and Longs and Big Decimals 

so map.get("<map name>", codec.String) would be optimal for above yeah ?

**Comment by jackygurui** [comment]
It seems StringCodec is your answer based on your current usage, I am afraid. 

Just wondering if you considered the option of turning `(Number) operationEntry[1][j])` into a `RAtomicLong` or `RAtomicDouble` before putting them into the map? Redisson lets you have embedded data structure that is not supported natively by Redis itself.

**Comment by mrniko** [comment]
Please rebase

**Comment by mrniko** [comment]
Thanks!

**Pull request merged**
