### PR TITLE
Allow LiveObjectService to work with classes that inherit from REntities

### PR DESCRIPTION
**Pull request by sdjacobs**
Addresses issue #930 

I hope I caught all the relevant usages of `@REntity` and `@RId`. See the additional test `RedissonLiveObjectServiceTest.testInheritedREntity()` to see an example.

### CODE REVIEW

**Comment by mrniko** [comment]
Thank you very much for your contribution!

**Comment by salilgandhi** [comment]
Parent -child is still not working for me. I am getting no such field exception when the RId is a part of the parent class. Can you please guide? What am I missing?

Redis loading failed.java.lang.NoSuchFieldException: No such field: guid
java.lang.IllegalArgumentException: java.lang.NoSuchFieldException: No such field: guid
	at org.redisson.liveobject.misc.ClassUtils.getField(ClassUtils.java:105)
	at org.redisson.RedissonLiveObjectService.persist(RedissonLiveObjectService.java:163)
	at org.redisson.RedissonLiveObjectService.merge(RedissonLiveObjectService.java:152)

**Comment by mrniko** [comment]
@salilgandhi 
It would be great if you can provide any test case to reproduce it.

**Comment by salilgandhi** [comment]
Hi Nikita,

Thanks for quick response!
Here is my base class:
@REntity
public abstract class AbstractDo implements Serializable {

	private static final long serialVersionUID = 7680440665187761533L;

	
	private @RId String guid;


	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Override
	public int hashCode() {
...	
}

	@Override
	public boolean equals(Object obj) {
...
}

My Derived Class:
@REntity
public class UserProfile extends AbstractDo {

    private static final long serialVersionUID = -7817007972557889495L;
    private String enterpriseGuid;


    @Auditable
    private String defaultStoreGuid;


    private @Indexed Set<String> roleGuids = new LinkedHashSet<String>();

    public static final String LOGIN_ID = "loginId";
    private @Indexed String  loginId;
   // private String  loginId;
    
    public static final String USER_ASSIGNMENTS = "assignments";
    
    @Auditable
    private Set<UserProfileAssignment> assignments = new LinkedHashSet<UserProfileAssignment>();

    public UserProfile(Set<UserProfileAssignment> assignments) {

        setAssignments(assignments);
    }

    public UserProfile() {

        assignments.add(new UserProfileAssignment());
    }

    public String getEnterpriseGuid() {
        return enterpriseGuid;
    }

    public void setEnterpriseGuid(String enterpriseGuid) {
        this.enterpriseGuid = enterpriseGuid;
    }

    public String getDefaultStoreGuid() {
        return defaultStoreGuid;
    }
...
...
}

And this is how I invoke it:
public class UserProfileRedisRadisson {
	
	 @Autowired
	   	private RedissonClient redissonClient;
	 
	
	public void loadData(Collection<UserProfile> allRows) {
		
		RLiveObjectService liveObjectService = redissonClient.getLiveObjectService();
		System.out.println("START");
		for(UserProfile ur:allRows) {
			if(liveObjectService.get(UserProfile.class, ur.getGuid()).getGuid() == null) {
				liveObjectService.persist(liveObjectService.attach(ur));
			} else {
				liveObjectService.merge(liveObjectService.attach(ur));
			}
		}
		System.out.println("END");
	}
}

Thanks,
Salil

**Comment by mrniko** [comment]
@salilgandhi 

Thanks for test case! Could you move it to a separate issue?

**Comment by salilgandhi** [comment]
@mrniko 
As requested moved to issue: https://github.com/redisson/redisson/issues/1126

Thanks,
Salil Gandhi

**Pull request merged**
