### PR TITLE
RedissonLocalCachedMap doesn't work with SerializationCodec or FstCodec

### PR DESCRIPTION
**Pull request by jribble**
Add a version of RedissonLocalCachedMapTest that uses the SerializationCodec.
Fix most of the tests by making classes implement Serializable.
The testAddAndGet test is still failing and after an hour of looking through it, I still can't figure why. It has something to do with encoding the key, which is an Integer object, and then redis gives the error: ERR hash value is not a valid float

So this pull request gets most of the way there, but I'm still missing the last part of making RedissonLocalCachedMap (tests) work with SerializationCodec.

### CODE REVIEW

**Comment by mrniko** [comment]
@jribble 
> The testAddAndGet test is still failing and after an hour of looking through it, I still can't figure why

`addAndGet` method doesn't use codec to add number to current map value.

**Comment by jribble** [comment]
@mrniko even so, that test fails when using SerializationCodec.

**Comment by mrniko** [comment]
@jribble https://redis.io/commands/hincrby can't add number to values serialized by SerilazationCodec only to plain numbers stored in redis.

**Comment by jribble** [comment]
So it's okay that this test fails when using SerializationCodec?

**Comment by jribble** [comment]
The test is now skipped. This should be good to go.

**Comment by mrniko** [comment]
Cool! Thank you!

**Pull request merged**
