### PR TITLE
Enable DNS TCP fallback when UDP query timeout

### PR DESCRIPTION
**Pull request by hellojukay**
https://github.com/redisson/redisson/issues/5572

### CODE REVIEW

**Comment by mrniko** [comment]
Thanks for the proposed change. Please correct all checks

**Comment by hellojukay** [comment]
> Thanks for the proposed change. Please correct all checks

I has fixed the ci check

**Comment by hellojukay** [comment]
@mrniko Do you have any plans to merge this PR?

**Comment by mrniko** [comment]
@hellojukay 

There is a problem that it doesn't compatible with the previous netty versions.

**Comment by OS-tariqabbasi** [comment]
@hellojukay @mrniko Was there a reason for not also making this change to `SequentialDnsAddressResolverFactory` and `RoundRobinDnsAddressResolverGroupFactory`?

**Comment by mrniko** [comment]
@OS-tariqabbasi 

Good point!

**Comment by mrniko** [comment]
@OS-tariqabbasi 

Fixed in https://github.com/redisson/redisson/commit/d4074e8afb7b29e1c0aa623e5c6404f4973dbee8

**Pull request merged**
