### PR TITLE
Call init before connect so watch dogs are instantiated with a timer.

### PR DESCRIPTION
**Pull request by johnou**
Fixes https://github.com/redisson/redisson/issues/671

### CODE REVIEW

**Comment by johnou** [comment]
Null check in org.redisson.client.RedisClient#RedisClient(io.netty.util.Timer, java.util.concurrent.ExecutorService, io.netty.channel.EventLoopGroup, java.lang.Class<? extends io.netty.channel.socket.SocketChannel>, java.lang.String, int, int, int) wouldn't hurt either..

**Comment by mrniko** [comment]
Thanks for attempt, but such fix would be wrong. `setMasterAddress`, `addSlaveAddress` method should be called before `init(this.config);` line.

**Comment by johnou** [comment]
ok so the timer needs to be instantiated sooner, any suggestions on how to restructure the init sequence?

**Comment by johnou** [comment]
I also noticed that the timer field in RedisClient is never assigned so the stop would throw an NPE when shutdown is invoked (if hasOwnGroup is true).

**Comment by johnou** [comment]
@mrniko PTAL.

**Comment by johnou** [comment]
I will open a new PR so the title is correct.

**Pull request closed without merging**
