### PR TITLE
Initialize LinkedHashMap with correct initial size to avoid resizing

### PR DESCRIPTION
**Pull request by theigl**
We are seeing a lot of allocations coming from `ObjectMapReplyDecoder` in production. The culprit is `LinkedHashMap.resize()`.

The map is currently sized with `parts.size()\2`, but doesn't take the default load factor of the map into account. This PR uses the same approach as [Guava](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Maps.java#L286) to prevent additional resizes.

Is there a utility class where the sizing logic could be centralized? I'm not very happy about the code duplication.

### CODE REVIEW

**Comment by mrniko** [comment]
Thanks for the proposed changes.

> Is there a utility class where the sizing logic could be centralized?

You can add a static factory method to MultiDecoder interface.

**Comment by theigl** [comment]
> You can add a static factory method to MultiDecoder interface.

Done. Although to me the factory method seems a little off place in `MultiDecoder`.

**Comment by mrniko** [comment]
Please correct checks

**Comment by theigl** [comment]
I reformatted the offending lines. I hope the checks pass now.

**Comment by mrniko** [comment]
Thanks for contribution!

**Pull request merged**
