### PR TITLE
add additional setRate methods to rate limiters

### PR DESCRIPTION
**Pull request by pc-mmautner**
Addresses https://github.com/redisson/redisson/issues/2322

### CODE REVIEW

**Comment by matthewbogner** [comment]
@mrniko I am aware you have proposed some workarounds in #2322, but I am curious what the opposition to this change is.  Would you be willing to elaborate further on why this change is not acceptable?

**Comment by mrniko** [comment]
@matthewbogner 

I expecting that object could be initialized only once.

**Comment by matthewbogner** [comment]
@mrniko thanks for responding.  Our situation is that we expect to be able to change the rate limit at runtime.  In our specific situation, we are controlling the rate of indexing operations to our elasticsearch cluster.  When/if we experience issues overloading our cluster with writes, we want to be able to adjust the rate limit down.  

This requires changing the rate of an existing rate limit object, which this pull request allows in a manor consistent with the rest of the redisson programmatic paradigms.  We can work around the issue but the manner in which this should be done is non-obvious to new consumers of the api.

**Comment by mrniko** [comment]
I see, I'll introduce `updateRateLimit` method of this purpose.

**Comment by matthewbogner** [comment]
Thank you!

**Comment by liwanghonggc** [comment]
@matthewbogner @mrniko ，Hello，I also meet the problem that I need to change the rate limit at runtime. How can I do this without the setRate method，my redisson version is 3.13.3. Thank you for your answer!

**Comment by mrniko** [comment]
added in https://github.com/redisson/redisson/issues/2322

**Comment by mrniko** [comment]
> How can I do this without the setRate method

just delete it first.

**Pull request closed without merging**
