### PR TITLE
PR for issue #2555

### PR DESCRIPTION
**Pull request by ouyangshixiong**
Using cascade persist on rlo objects with cycle reference will cause infinite loop or StackOverFlow Exception.
But it's also import that I should modify less code, cause more modifications may cause more bugs
After think much about how to setup graph，how to persist vertex，how to persist edge.
Finally, I got this PR, pls review it, thanks.

[this link is my test case for the feature: ](https://github.com/ouyangshixiong/redisson-test/blob/master/src/main/java/com/example/controller/AdvRLOController.java)

### CODE REVIEW

**Comment by mrniko** [comment]
Thanks for the contribution, but all logic should be in the same persist method.

**Comment by ouyangshixiong** [comment]
> Thanks for the contribution, but all logic should be in the same persist method.

Well, If use just one persist method, user have to pass the whole graph(all rlo objects) as parameter once.  Is it what you prefer ?

**Comment by mrniko** [comment]
I expect that nothing should be changed in API interface. Can we do that?

**Comment by ouyangshixiong** [comment]
> I expect that nothing should be changed in API interface. Can we do that?

Sure, I can override this api  <T> List<T> persist(T... detachedObjects);
I think the method has no relationship with other methods,.
I can change this method's default implementation without change api

**Comment by ouyangshixiong** [comment]
close this PR cause I have suggest a new PR [#2578](https://github.com/redisson/redisson/pull/2578)

**Pull request closed without merging**
